# Defines the matching rules for Guard.

guard :minitest, spring: true, all_on_start: false do
    watch(%r{^test/(.*)/?(.*)_test\.rb$})
    watch('test/test_helper.rb') { 'test' }
    watch('config/routes.rb')    { integration_tests }
    watch(%r{^app/models/(.*?)\.rb$}) do |matches|
        "test/models/#{matches[1]}_test.rb"
    end
    watch(%r{^app/controllers/(.*?)_controller\.rb$}) do |matches|
        resource_tests(matches[1])
    end
    watch(%r{^app/views/([^/]*?)/.*\.html\.erb$}) do |matches|
        [integration_tests(matches[1]), controller_test(matches[1])]
    end
    watch(%r{^app/helpers/(.*?)_helper\.rb$}) do |matches|
        [integration_tests(matches[1]), controller_test(matches[1]), helper_test(matches[1])]
    end
    watch('app/helpers/sessions_helper.rb') do
        [integration_tests, 'test/controllers/sessions_controller_test.rb', 'test/helpers/sessions_helper_test.rb']
    end
    watch('app/controllers/application_controller.rb') do
        resource_tests
    end
end

# Returns the integration tests corresponding to the given resource.
def integration_tests(resource = :all)
    if resource == :all
        Dir["test/integration/*"]
    else
        Dir["test/integration/#{resource}_*.rb"]
    end
end

# Returns the controller tests corresponding to the given resource.
def controller_test(resource = :all)
    if resource == :all
        Dir["test/controllers/*"]
    else
        Dir["test/controllers/#{resource}_controller_test.rb"]
    end
end

# Returns the model tests corresponding to the given resource.
def model_test(resource = :all)
    if resource == :all?
        Dir["test/models/*"]
    else
        resource = resource.to_s.chop
        Dir["test/models/#{resource}_test.rb"]
    end
end

def helper_test(resource)
    Dir["test/helpers/#{resource}_helper_test.rb"]
end

# Returns all tests for the given resource.
def resource_tests(resource = :all)
    [integration_tests(resource), controller_test(resource), model_test(resource)]
end

# Guard-Rails supports a lot options with default values:
# daemon: false                        # runs the server as a daemon.
# debugger: false                      # enable ruby-debug gem.
# environment: 'development'           # changes server environment.
# force_run: false                     # kills any process that's holding the listen port before attempting to (re)start Rails.
# pid_file: 'tmp/pids/[RAILS_ENV].pid' # specify your pid_file.
# host: 'localhost'                    # server hostname.
# port: 3000                           # server port number.
# root: '/spec/dummy'                  # Rails' root path.
# server: thin                         # webserver engine.
# start_on_start: true                 # will start the server when starting Guard.
# timeout: 30                          # waits untill restarting the Rails server, in seconds.
# zeus_plan: server                    # custom plan in zeus, only works with `zeus: true`.
# zeus: false                          # enables zeus gem.
# CLI: 'rails server'                  # customizes runner command. Omits all options except `pid_file`!

guard 'rails' do
    watch('Gemfile.lock')
    watch(%r{^(config|lib)/.*})
end
