development:
    adapter: postgresql
    database: exeter_development
    host: localhost
    pool: 5
    timeout: 5000
    username: Shaun
    password:

test:
    adapter: postgresql
    database: exeter_test
    host: localhost
    pool: 5
    timeout: 5000
    username: Shaun
    password:
